# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Masamichi Ueta
description: エンジニアリング・デザイン・日常

url: https://masamichi.me
twitter_username: masamichiueta
github_username:  masamichiueta
author: masamichiueta
lang: ja_JP

paginate: 10

# Build settings
markdown: kramdown
future: true

category_slugs:
  cryptocurrency: "暗号通貨"
  development: "開発"
  family: "家族"
  design: "デザイン"
  gadget: "ガジェット"
  apps: "アプリ"
  hobby: "趣味"

plugins:
  - jekyll-gist
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-category-pages
  - jekyll-sitemap
